version: '3.8'

services:
  # The CPP Server
  cpp_server:
    build:
      context: .
      dockerfile: Dockerfile.cpp 
    container_name: cpp_server_container
    ports:
      - "5555:5555"
    networks:
      - ex3_net
    volumes:
      - ./data_files:/app/data_files
    environment:
      - MY_FILE_PATH=/app/data_files

  # Node.js server
  node_server:
    build:
      context: .
      dockerfile: Dockerfile.node 
    container_name: node_server_container
    ports:
      - "3000:3000"
    networks:
      - ex3_net
    depends_on:
      - cpp_server # wait for the cpp server
    environment:
      - CPP_SERVER_HOST=cpp_server
      - CPP_SERVER_PORT=5555

networks:
  ex3_net:
    driver: bridge