version: '3.8'

services:
  # 1. MongoDB Service
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27018:27017"
    networks:
      - ex3_net
    volumes:
      - mongo_data:/data/db

  # 2. C++ Server
  cpp_server:
    build:
      context: .
      dockerfile: Dockerfile.cpp 
    container_name: cpp_server_container
    ports:
      - "5555:5555"
    networks:
      - ex3_net
    volumes:
      - ./data_files:/app/data_files
    environment:
      - MY_FILE_PATH=/app/data_files
      - THREAD_POOL_SIZE=10

  # 3. Node.js Server
  node_server:
    build:
      context: .
      dockerfile: Dockerfile.node 
    container_name: node_server_container
    ports:
      - "3000:3000"
    networks:
      - ex3_net
    depends_on:
      - cpp_server 
      - mongo 
    environment:
      - CPP_SERVER_HOST=cpp_server
      - CPP_SERVER_PORT=5555
      - MONGO_URI=mongodb://mongo:27017/my_drive_db
      - PORT=3000

  # 4. React Native Client (עכשיו משתמש ב-Dockerfile.expo)
  react_client:
    build:
      context: .
      dockerfile: Dockerfile.expo  # <--- השינוי החשוב!
    container_name: react_client_container
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    networks:
      - ex3_net
    depends_on:
      - node_server
    environment:
      # תמיד תוודאי שזה ה-IP האמיתי שלך באותו רגע
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.142
      - EXPO_PUBLIC_API_URL=http://192.168.1.142:3000/api
    stdin_open: true
    tty: true

networks:
  ex3_net:
    driver: bridge

volumes:
  mongo_data: